name: Build FFmpeg for MacOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-13, macos-latest ]
        include:
          - os: macos-13
            arch: x86_64
            artifact_name: ffmpeg-macos-x86_64
          - os: macos-latest
            arch: aarch64
            artifact_name: ffmpeg-macos-aarch64

    steps:
      - name: Install dependencies
        run: |
          brew install automake libtool nasm pkg-config yasm

      - name: Download FFmpeg source code
        run: |
          git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
          cd ffmpeg

      - name: Configure FFmpeg
        run: |
          cd ffmpeg
          ./configure --disable-everything \
            --disable-ffprobe \
            --enable-ffmpeg \
            --enable-avformat \
            --enable-avcodec \
            --enable-avutil \
            --enable-decoder=srt \
            --enable-decoder=movtext \
            --enable-decoder=webvtt \
            --enable-decoder=ass \
            --enable-decoder=ssa \
            --enable-decoder=subrip \
            --enable-encoder=srt \
            --enable-encoder=subrip \
            --enable-encoder=movtext \
            --enable-demuxer=mov \
            --enable-demuxer=matroska \
            --enable-demuxer=ass \
            --enable-demuxer=srt \
            --enable-demuxer=webvtt \
            --enable-muxer=srt \
            --enable-protocol=file \
            --enable-static \
            --disable-shared \
            --disable-autodetect \
            --pkg-config-flags="--static"

      - name: Build and install FFmpeg
        run: |
          cd ffmpeg
          make -j$(nproc)
          sudo make install


      - name: Verify static linking
        run: |
          echo "=== Dynamic dependencies ==="
          otool -L /usr/local/bin/ffmpeg
          echo "=== File info ==="
          file /usr/local/bin/ffmpeg

      - name: Test FFmpeg functionality
        run: |
          echo "=== 测试 FFmpeg 基本功能 ==="
          /usr/local/bin/ffmpeg -version
          
          echo "=== 测试支持的编解码器 ==="
          /usr/local/bin/ffmpeg -encoders | grep -E "(srt|subrip|movtext)" || echo "没找到字幕编码器"
          /usr/local/bin/ffmpeg -decoders | grep -E "(srt|movtext|webvtt|ass|ssa)" || echo "没找到字幕解码器"
          
          echo "=== 测试支持的格式 ==="
          /usr/local/bin/ffmpeg -formats | grep -E "(mov|matroska|srt)" || echo "没找到支持的格式"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            /usr/local/bin/ffmpeg