name: UI Test

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Tests on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # 限制同时运行的作业数量，避免资源竞争
      max-parallel: 1
      matrix:
        os: [windows-latest, macos-13, macos-latest]
        include:
          - os: windows-latest
            arch: x64
            name: Windows x86_64
          - os: macos-13
            arch: x64
            name: macOS x86_64
          - os: macos-latest
            arch: aarch64
            name: macOS aarch64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Set execute permissions on gradlew
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      # macOS 平台使用单线程运行测试
      - name: Run UI tests (macOS)
        if: runner.os == 'macOS'
        run: ./gradlew uiTest --max-workers=1 --no-daemon

      # 其他平台使用默认配置
      - name: Run UI tests (other platforms)
        if: runner.os != 'macOS'
        run: ./gradlew uiTest