name: UI Test

on:
  workflow_dispatch:


jobs:
  test:
    name: Run Tests on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # 限制同时运行的作业数量，避免资源竞争
      max-parallel: 1
      matrix:
        os: [windows-latest, macos-13, macos-latest]
        include:
          - os: windows-latest
            arch: x64
            name: Windows x86_64
            run_tests: true
          - os: macos-13
            arch: x64
            name: macOS x86_64
            run_tests: false
          - os: macos-latest
            arch: aarch64
            name: macOS aarch64
            run_tests: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Set execute permissions on gradlew
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Set UTF-8 encoding for Windows
        if: runner.os == 'Windows'
        run: |
          # 设置 Gradle 的 JVM 参数，强制使用 UTF-8 编码
          # 解决 Windows 环境下中文字符显示为问号的问题
          echo "GRADLE_OPTS=-Dfile.encoding=UTF-8 -Dstdout.encoding=UTF-8 -Dstderr.encoding=UTF-8" >> $env:GITHUB_ENV


      # 只在 Windows 上运行完整 UI 测试
      - name: Run UI tests
        if: matrix.run_tests
        run: ./gradlew uiTest

      # 在 macOS 上只编译测试但不运行，确保代码至少可以编译
      - name: Compile tests only (macOS)
        if: runner.os == 'macOS'
        run: ./gradlew compileTestKotlin

      # 在 macOS 上留下说明
      - name: Skip macOS UI Tests
        if: runner.os == 'macOS'
        run: |
          echo "UI 测试在 macOS 平台上被跳过，因为 GitHub Actions 环境中存在 JVM 崩溃问题 (退出代码 134)"
          echo "这些测试仍然在 Windows 平台上运行，并在本地开发环境中可正常运行"
